# Generated by Django 3.0.3 on 2020-02-14 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseProvider', '0002_auto_20200213_2310'),
        ('purchasedProducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedproducts',
            options={'verbose_name_plural': 'Compras'},
        ),
        migrations.AddField(
            model_name='purchasedproducts',
            name='purchase_type',
            field=models.CharField(choices=[('Avulso', 'Avulso'), ('NFE', 'Nota Fiscal')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasedproducts',
            name='purchased_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='purchaseProvider.PurchasedProvider'),
            preserve_default=False,
        ),
    ]
