# Generated by Django 3.0.3 on 2020-02-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasedProducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedproducts',
            name='purchase_type',
            field=models.CharField(choices=[('Avulso', 'Avulso'), ('NFE', 'Nota Fiscal')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
