version: '3.7'

services:
  django:
    build: ./
    container_name: projectbbk
    restart: always
    ports:
      - '8080:8080'

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'
