# Generated by Django 3.0.3 on 2020-02-16 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200216_0100'),
        ('stock', '0003_auto_20200213_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'estoque', 'verbose_name_plural': 'Estoque'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='Produto'),
        ),
    ]
