# Generated by Django 3.0.3 on 2020-02-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20200213_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'um cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Cargo'),
        ),
    ]
