# Generated by Django 3.0.3 on 2020-02-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseProvider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Desconhecido', max_length=120)),
                ('note_number', models.IntegerField(default=99999)),
                ('purchase_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Compras com o fornecedor',
            },
        ),
        migrations.DeleteModel(
            name='Detached',
        ),
    ]
