# Generated by Django 3.0.3 on 2020-02-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseProvider', '0002_auto_20200213_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedprovider',
            options={'verbose_name_plural': 'Registrar Compras'},
        ),
        migrations.AddField(
            model_name='purchasedprovider',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
