# Generated by Django 3.0.3 on 2020-02-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseProvider', '0003_auto_20200213_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedprovider',
            name='note_number',
            field=models.IntegerField(unique=True),
        ),
    ]
