# Generated by Django 3.0.3 on 2020-02-15 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20200214_2350'),
        ('purchaseProvider', '0004_auto_20200214_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedprovider',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider.Provider'),
        ),
    ]
