# Generated by Django 3.0.3 on 2020-02-15 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseProvider', '0005_auto_20200214_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedprovider',
            old_name='name',
            new_name='provider',
        ),
    ]
