# Generated by Django 3.0.3 on 2020-02-15 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200213_1938'),
        ('purchaseProvider', '0006_auto_20200214_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('Avulso', 'Avulso'), ('NFE', 'Nota Fiscal')], max_length=15)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product')),
                ('purchased_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchaseProvider.PurchasedProvider')),
            ],
            options={
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
