# Generated by Django 3.0.3 on 2020-02-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseProvider', '0007_purchasedproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedproducts',
            options={'verbose_name_plural': 'Produtos Comprado'},
        ),
        migrations.AlterModelOptions(
            name='purchasedprovider',
            options={'verbose_name_plural': 'Compras'},
        ),
        migrations.RemoveField(
            model_name='purchasedprovider',
            name='total',
        ),
    ]
