# Generated by Django 3.0.3 on 2020-02-16 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20200216_0100'),
        ('product', '0004_auto_20200216_0100'),
        ('purchaseProvider', '0008_auto_20200215_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='purchasedproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='purchasedproducts',
            name='purchase_type',
            field=models.CharField(choices=[('Avulso', 'Avulso'), ('NFE', 'Nota Fiscal')], max_length=15, verbose_name='Tipo da Compra'),
        ),
        migrations.AlterField(
            model_name='purchasedproducts',
            name='purchased_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchaseProvider.PurchasedProvider', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='purchasedproducts',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='purchasedprovider',
            name='note_number',
            field=models.IntegerField(unique=True, verbose_name='Numero da Nota'),
        ),
        migrations.AlterField(
            model_name='purchasedprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider.Provider', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='purchasedprovider',
            name='purchase_date',
            field=models.DateField(verbose_name='Data da Compra'),
        ),
    ]
