# Generated by Django 3.0.3 on 2020-02-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rg',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
