# Generated by Django 3.0.3 on 2020-02-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20200212_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Clientes'},
        ),
    ]
