# Generated by Django 3.0.3 on 2020-02-20 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_address_number'),
        ('client', '0005_auto_20200216_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address', verbose_name='Endereço'),
        ),
    ]
