# Generated by Django 3.0.3 on 2020-02-15 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0004_auto_20200213_1938'),
        ('paymentMethod', '0002_auto_20200215_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.Client')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paymentMethod.PaymentMethod')),
            ],
            options={
                'verbose_name_plural': 'Vendas',
            },
        ),
    ]
