# Generated by Django 3.0.3 on 2020-02-16 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20200216_0100'),
        ('product', '0004_auto_20200216_0100'),
        ('paymentMethod', '0003_auto_20200216_0100'),
        ('sale', '0003_auto_20200215_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'uma venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AlterModelOptions(
            name='saleproduct',
            options={'verbose_name': 'um produto vendido', 'verbose_name_plural': 'Produtos Vendidos'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.Client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paymentMethod.PaymentMethod', verbose_name='Metodo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Total da Venda'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Desconto'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.Sale', verbose_name='Venda'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total'),
        ),
    ]
