# Generated by Django 3.0.3 on 2020-02-20 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20200216_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Venda'),
            preserve_default=False,
        ),
    ]
