# Generated by Django 3.0.3 on 2020-02-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logslogin',
            options={'verbose_name': 'um log', 'verbose_name_plural': 'Logs de atutenticação'},
        ),
    ]
