# Generated by Django 3.0.3 on 2020-02-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentMethod', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name_plural': 'Metodo de pagamento'},
        ),
    ]
