# Generated by Django 3.0.3 on 2020-02-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentMethod', '0002_auto_20200215_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'um metodo de pagamento', 'verbose_name_plural': 'Metodo de pagamento'},
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='mode',
            field=models.CharField(max_length=120, verbose_name='Modo de pagamento'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='type_payment',
            field=models.CharField(max_length=120, verbose_name='Tipo de pagamento'),
        ),
    ]
