# Generated by Django 3.0.3 on 2020-02-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name_plural': 'Fornecedores'},
        ),
    ]
