# Generated by Django 3.0.3 on 2020-02-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20200213_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
