# Generated by Django 3.0.3 on 2020-02-11 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fantasy_name', models.CharField(max_length=200, unique=True)),
                ('social_registration', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('state_registration', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('open_date', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
    ]
