# Generated by Django 3.0.3 on 2020-02-11 17:12

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
    ]
