# Generated by Django 3.0.3 on 2020-02-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Empresa'},
        ),
    ]
