# Generated by Django 3.0.3 on 2020-02-16 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20200216_0100'),
        ('company', '0003_auto_20200213_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'uma empresa', 'verbose_name_plural': 'Empresa'},
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Address', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fantasy_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company', verbose_name='Logo da Empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='open_date',
            field=models.DateField(verbose_name='Data de Abertura'),
        ),
        migrations.AlterField(
            model_name='company',
            name='social_registration',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Registro Social'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state_registration',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Registro Estadual'),
        ),
    ]
