# Generated by Django 3.0.3 on 2020-02-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200216_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='social_registration',
        ),
        migrations.AddField(
            model_name='company',
            name='social_reason',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state_registration',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Inscrição Estadual'),
        ),
    ]
