# Generated by Django 3.0.3 on 2020-02-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('complement', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
