# Generated by Django 3.0.3 on 2020-02-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20200212_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Endereço'},
        ),
    ]
