# Generated by Django 3.0.3 on 2020-02-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200213_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'um endereço', 'verbose_name_plural': 'Endereço'},
        ),
        migrations.AlterField(
            model_name='address',
            name='cep',
            field=models.CharField(max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(max_length=200, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=200, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=200, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='address',
            name='uf',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
    ]
