# Generated by Django 3.0.3 on 2020-02-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20200216_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Numero'),
            preserve_default=False,
        ),
    ]
